; interrupt vectors
SECTION "vblank",ROM0[$40]
	jp VBlank
SECTION "lcdstat",ROM0[$48]
	jp LCDInterrupt
SECTION "timer",ROM0[$50]
	reti
SECTION "serial",ROM0[$58]
	reti
SECTION "joypad",ROM0[$60]
	reti

SECTION "Header", ROM0[$100]
	di ; entry point
	jp EntryPoint

    ; allocate space for the header generated by RGBFIX
	DS $150 - @, 0